blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name="all_blogs"),
    path('<int:blog_id>/',views.detail, name="detail")
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'
urlpatterns = [
    path('', views.home, name='home')
]

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
        title = models.CharField(max_length=100)
        description = models.CharField(max_length=250)
        image = models.ImageField(upload_to='portfolio/images/')
        url = models.URLField(blank=True)

        def __str__(self):
                return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.
def all_blogs(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html',{
        'blogs': blogs
    })
def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html',{
        'blog':blog
    })

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request,'portfolio/home.html', {
        'projects':projects
    })

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}
    <h1 id="blogtitle" class="font-weight-bold text-center">Hello Blogs!!</h1>

    <h2 class="text-center mb-5" >Rohit has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h2>

    {% for blog in blogs %}
    <div class="row justify-content-center my-3">
        <div class="col-md-10">
            <a href="{% url 'blog:detail' blog.id %}"><h1>{{ blog.title }}</h1></a>
            <h5>{{ blog.date|date:'M d Y'|upper }}</h5>
            <p>{{ blog.description | safe |truncatechars:100 }}</p>
        </div>

    </div>

    {% endfor %}
{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}
    <h1 id="blogdetailtitle"  class="text-center mt-5">{{ blog.title }}</h1>
    <h2 class="text-center text-muted mb-5">{{ blog.date | date:'F jS Y' }}</h2>
    <p>{{ blog.description|safe }}</p>
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

      <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">
      <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <title>Rohit's Portfolio</title>
  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand btn btn-Link" href="{% url 'portfolio:home' %}">Home</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
        <li>

        </li>
    </ul>

    <a class="link mr-3" href="{% static 'portfolio/Rohit-Resume.pdf' %}" target="_blank">Resume</a>

    <a class="link mr-3" href="https://www.linkedin.com/in/rohit-s-001591192/" target="_blank">LinkedIn</a>

    <a href="{% url 'blog:all_blogs' %}" class="btn btn-primary my-2 my-sm-0" type="button">Blog</a>

  </div>
</nav>
<div class="container ml-5 mt-3">
{% block content %} {% endblock %}
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}



{% load static %}
<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/Rohit.jpg' %}" height="450px">
  </div>
</div>

<div class="row justify-content-center mb-3">
    <div class="col-9 text-center">
        <h1 id="hometext" class="font-weight-bold">Rohit Sav is a commander-in-Chief at Portfolio and lives in pune</h1>
    </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>

<div class="row">
    {% for project in projects %}
    <div class="col-lg-4 col-md-6">
        {% if project.url %}
            <br>
            <a href="{{ project.url }}">
                <img src="{{ project.image.url }}" class="img-fluid mb-2">
            </a>
        {% else %}
            <img src="{{ project.image.url }}" class="img-fluid mb-2">
        {% endif %}
        <h3>{{ project.title }}</h3>
        <p>{{ project.description }}</p>
    </div>
    {% endfor %}
</div>

{% endblock %}